# Generated by Django 3.1.7 on 2021-04-14 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0002_jsonentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jsonentry',
            old_name='jEntry',
            new_name='jentry',
        ),
    ]
