# Generated by Django 3.1.7 on 2021-04-14 22:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0003_auto_20210414_1508'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='jsonEntry',
            new_name='jsonFormEntry',
        ),
    ]
