# Generated by Django 3.1.7 on 2021-04-14 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0005_auto_20210414_1512'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jsonEntry',
        ),
    ]
