# Generated by Django 3.1.7 on 2021-04-14 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0007_jentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='jsonTestEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
