# Generated by Django 3.1.7 on 2021-04-15 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0009_delete_jsontestentry'),
    ]

    operations = [
        migrations.DeleteModel(
            name='jEntry',
        ),
    ]
