# Generated by Django 3.1.7 on 2021-04-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('htmlforms', '0010_delete_jentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='JsonEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry', models.JSONField()),
            ],
        ),
    ]
